# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba99708b694fc0818908d0031e991c448da4235426fdd2943623b26974cd91e4840986cbd73db9e5b4ce1ff1f780e902df0a582be99d86f2cab5bebe464944b9

test:
  secret_key_base: 80d4ed417df15de62f0c1de11da78b677415f021ec0d8f5e522bba23274d226177126ed395dc19773fde8f5dfe017085312b0010df8b5dd96418c9b9a214944e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
